### ISSUE TITLE
Wrong display

### ISSUE THREAD

**Issue by BackWheel** [GorgeousOne/NetherView#14]
When I destroy the nether portal, the plugin will still show the nether view!
server version: paper 1.15.2
plugin version: 1.0.0

plugin config:
```
portal-projection-view-distance: 16
portal-display-range: 32
hide-portal-blocks: true
cancel-teleport-when-linking-portals: true
worlds-with-projecting-portals:
- world
viewable-worlds:
- world_nether
```

**Comment by GorgeousOne** [comment]
How exactly did you destroy the portal?

**Comment by BackWheel** [comment]
After I successfully built the nether portal and after loading the nether view, I dug out one of the obsidian portals, which caused this to happen.

**Comment by BackWheel** [comment]
This problem seems to be fixed in the new version of the plug-in, so I close this problem
