### ISSUE TITLE
Portals display the wrong side of their destination

### ISSUE THREAD

**Issue by GorgeousOne** [GorgeousOne/NetherView#29]
Some portals show on one side a place in the nether but when players walks through the portal they actually arrive at the place of the nether the portal was showing on the other side.

I could not find any reliable way to solve this, so it will probably stay a bug for some time.

**Comment by LoneDev6** [comment]
You could fix the player look direction after they teleport to the nether

**Comment by GorgeousOne** [comment]
That. Is a very good idea.

**Comment by LoneDev6** [comment]
No problem ;) I can't wait to see it implemented, this is a great plugin
