### ISSUE TITLE
"Clipping" bug when standing at the portals edge

### ISSUE THREAD

**Issue by mfnalex** [GorgeousOne/NetherView#31]
If you stand at the very edge of the portal, the view gets clipped:

[GIF:](https://api.jeff-media.de/tmp/netherview-bug.gif)
![GIF](https://api.jeff-media.de/tmp/netherview-bug.gif)

I don't think it's a big problem or that it matters at all, but I wanted to report it just in case :)

(Running on Paper-353 if that matters)

**Comment by GorgeousOne** [comment]
Okay that's quiet a big portal you got there! xD But I'll look into it when I'm available again,

**Comment by mfnalex** [comment]
no problem, I don't think anyone will really care about that, I just wanted to mention it^^

**Comment by GorgeousOne** [comment]
Fixed (not published yet)
