### ISSUE TITLE
Allow non-obsidian blocks at portal frame corners

### ISSUE THREAD

**Issue by Bobcat00** [GorgeousOne/NetherView#52]
Opening an issue so we can discuss PR #51 further.

Real portal frames don't need any blocks at all on the corners, but I observed that air blocks allowed the portal projection to be seen at those locations. So my original PR required occluding blocks at the corners so the projection wouldn't be seen there.

As you pointed out, however, the block break listener explicitly checks for an obsidian block and then calls removeDamagedPortals. I suppose the check for obsidian can be changed to isOccluding(), which would result in removeDamagedPortals being called every time someone breaks a solid block.  Is that sufficient?  And do you have an idea how efficient that is?  I don't want to add a lot of extra load.  I guess it really depends on how many portals there are in that world.

**Comment by Bobcat00** [comment]
Just to make sure you know...  You have a couple of debug lines at https://github.com/GorgeousOne/NetherView/blob/b48ca2f93051b9f31c8901faa1c9b7133c9b26e4/src/main/java/me/gorgeousone/netherview/listeners/TeleportListener.java#L107
```
System.out.println(portal);
System.out.println(counterPortal);
```
I did a quick test and this version seems to be working.

**Comment by GorgeousOne** [comment]
Added to update 2.1.0
