### ISSUE TITLE
Make purple portal surface visible.

### ISSUE THREAD

**Issue by XfedeX** [GorgeousOne/NetherView#61]
Please make the nether_portal block visible (configurable in options), so there will be no more lighting issues (nether portal blocks make light.) and nether will be less visible making also latency less visible!

**Comment by GorgeousOne** [comment]
If I’m not mistaken the config has a setting for that:
hide-portal-blocks: false

**Comment by XfedeX** [comment]
Oh sorry GorgeousOne! D:
